os: osx
osx_image: xcode11.3
language: objective-c
cache:
  - bundler
  - cocoapods

stages:
  - checks
  - test

before_script:
  - '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger || echo "Skipping Danger for External Contributor"'

jobs:
  include:
    - stage: checks
      # This only needs to be run once, so restrict it to an arbitrary combination
      before_install:
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/e3496d9/Formula/clang-format.rb
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7963c3d/Formula/swiftformat.rb
        - pip install flake8
      script:
        - ./scripts/check.sh --test-only

    - stage: test
      env:
        - PROJECT=Storage PLATFORM=all METHOD=xcodebuild
      before_install:
        - ./scripts/if_changed.sh ./scripts/install_prereqs.sh
        - ./scripts/if_changed.sh ./scripts/setup_quickstart.sh storage
      script:
        - travis_retry ./scripts/if_changed.sh ./scripts/test_quickstart.sh storage
        - travis_retry ./scripts/if_changed.sh ./scripts/build.sh $PROJECT $PLATFORM
        - travis_retry ./scripts/if_changed.sh ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=ios
        - travis_retry ./scripts/if_changed.sh ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=tvos
        - travis_retry ./scripts/if_changed.sh ./scripts/pod_lib_lint.rb FirebaseStorage.podspec --skip-tests --platforms=macos

  # TODO(varconst): enable if it's possible to make this flag work on build
  # stages. It's supposed to avoid waiting for jobs that are allowed to fail
  # before reporting the results.
  # fast_finish: true

branches:
  only:
    - master
    - pb-qs
